# Generated by Django 3.2.6 on 2021-08-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
