# Generated by Django 3.2.4 on 2021-07-16 09:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomePostTitle', models.CharField(max_length=300)),
                ('HomePostTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('HomePostMetadata', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('HomePostImage', models.ImageField(default='HomePostImage.jpg', upload_to='HomePost')),
                ('HomePostBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('HomePostUrl', models.TextField()),
                ('HomePostAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
