# Generated by Django 3.2.8 on 2021-10-19 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DnsName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('DomainYear', models.CharField(max_length=50)),
                ('DomainAutoRenew', models.CharField(max_length=50)),
                ('DnsStatus', models.CharField(max_length=50)),
                ('DomainSsl', models.CharField(max_length=50)),
                ('DomainPremium', models.CharField(max_length=50)),
                ('NameServer1', models.CharField(max_length=50)),
                ('NameServer2', models.CharField(max_length=50)),
                ('IP', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=50)),
                ('PriceType', models.CharField(max_length=50)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
