# Generated by Django 3.2.6 on 2021-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta',
            field=models.TextField(),
        ),
    ]
