# Generated by Django 3.2.8 on 2021-10-23 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address1', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneCode', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('CustomerId', models.CharField(max_length=50)),
            ],
        ),
    ]
