# Generated by Django 3.2.6 on 2021-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomainSearch', '0002_dns_dnstlds'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsTlds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DnsTlds', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='dns',
            name='DnsTlds',
        ),
    ]
