# Generated by Django 3.2.6 on 2021-09-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckoutMoney', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutMoneyDb',
            new_name='CheckoutMoneyDbs',
        ),
    ]
