# Generated by Django 3.2.6 on 2021-09-24 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CheckoutMoney', '0002_rename_checkoutmoneydb_checkoutmoneydbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmoneydbs',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
