# Generated by Django 3.2.6 on 2021-09-25 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CheckoutMoney', '0003_checkoutmoneydbs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmoneydbs',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
