# Generated by Django 3.2.6 on 2021-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckoutMoney', '0004_alter_checkoutmoneydbs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmoneydbs',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
