# Generated by Django 3.2.8 on 2021-10-24 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomainName', models.CharField(max_length=50)),
                ('HostName', models.CharField(max_length=50)),
                ('IPv4Value', models.CharField(max_length=50)),
                ('TTL', models.CharField(max_length=50)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
