# Generated by Django 3.2.5 on 2021-07-19 04:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartPostTitle', models.CharField(max_length=200)),
                ('StoryPostBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('StoryPostBodyImage', models.ImageField(default='StartPostImage.jpg', upload_to='StartPostImage')),
                ('StoryPostTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('StoryPostAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
