# Generated by Django 3.2.6 on 2021-10-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DnsName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailField', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=50)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DnsEmailForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('forward', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DnsIdPros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('IdPro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DnsManRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('RecordType', models.CharField(max_length=50)),
                ('HostName', models.CharField(max_length=50)),
                ('IpAddress', models.CharField(max_length=50)),
                ('Ttl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DnsRegisterPrivateNameserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('Nameserver', models.CharField(max_length=50)),
                ('NameserverIp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DnsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('Nameserver1', models.CharField(max_length=50)),
                ('Nameserver2', models.CharField(max_length=50)),
                ('Nameserver3', models.CharField(max_length=50)),
                ('Nameserver4', models.CharField(max_length=50)),
                ('Nameserver5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransferDomainUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DnsName', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhoisInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DnsName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailField', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=50)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
