# Generated by Django 3.2.8 on 2021-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnsSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='CustomerId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admininformation',
            name='PhoneCode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admininformation',
            name='ReContactId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admininformation',
            name='ZipCode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoisinformation',
            name='CustomerId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoisinformation',
            name='PhoneCode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoisinformation',
            name='ReContactId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoisinformation',
            name='ZipCode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
