# Generated by Django 3.2.4 on 2021-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepost',
            name='HomePostBody',
        ),
        migrations.AlterField(
            model_name='homepost',
            name='HomePostUrl',
            field=models.CharField(max_length=300),
        ),
    ]
