# Generated by Django 3.2.4 on 2021-07-16 20:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoryPostImage', models.ImageField(default='StoryPostImage.jpg', upload_to='StoryPost')),
                ('StoryPostTitle', models.CharField(max_length=200)),
                ('StoryPostTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('StoryPostMetadata', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('StoryPostBody1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('StoryPostBodyImage1', models.ImageField(default='StoryPost/BodyImage.jpg', upload_to='StoryPost/BodyImage')),
                ('StoryPostBody2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('StoryPostBodyImage2', models.ImageField(default='StoryPost/BodyImage.jpg', upload_to='StoryPost/BodyImage')),
                ('StoryPostBody3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('StoryPostUrl', models.CharField(max_length=300)),
                ('StoryPostAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
