# Generated by Django 3.2.4 on 2021-07-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypost',
            old_name='StoryPostBodyImage1',
            new_name='StoryPostBodyImage',
        ),
        migrations.RemoveField(
            model_name='storypost',
            name='StoryPostBodyImage2',
        ),
    ]
