# Generated by Django 3.2.6 on 2021-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('test', models.CharField(blank=True, max_length=60, null=True)),
                ('UserName', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
            ],
        ),
    ]
