# Generated by Django 3.2.6 on 2021-09-14 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalinformation',
            name='test',
        ),
        migrations.AddField(
            model_name='userpersonalinformation',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
