# Generated by Django 3.2.6 on 2021-09-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0003_dnsinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnsinformation',
            old_name='DnsPrimum',
            new_name='DnsPremium',
        ),
    ]
