# Generated by Django 3.2.6 on 2021-09-14 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0004_rename_dnsprimum_dnsinformation_dnspremium'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcannModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('DnsTime', models.CharField(max_length=50)),
                ('DnsPrivacy', models.CharField(max_length=50)),
                ('DnsSsl', models.CharField(max_length=50)),
                ('DnsPremium', models.CharField(max_length=50)),
                ('DnsName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
