# Generated by Django 3.2.6 on 2021-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0005_icannmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsinformation',
            name='NameServer1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsinformation',
            name='NameServer2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='NameServer1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='NameServer2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
