# Generated by Django 3.2.6 on 2021-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0006_auto_20210914_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsinformation',
            name='DnsStatus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
