# Generated by Django 3.2.6 on 2021-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0007_dnsinformation_dnsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsinformation',
            name='DomainAutoRenew',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='dnsinformation',
            name='DomainPremium',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='dnsinformation',
            name='DomainSsl',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='dnsinformation',
            name='DnsStatus',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
