# Generated by Django 3.2.6 on 2021-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0009_auto_20210915_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icannmodel',
            old_name='DnsPremium',
            new_name='DnsStatus',
        ),
        migrations.RenameField(
            model_name='icannmodel',
            old_name='DnsPrivacy',
            new_name='DomainAutoRenew',
        ),
        migrations.RenameField(
            model_name='icannmodel',
            old_name='DnsSsl',
            new_name='DomainPremium',
        ),
        migrations.RemoveField(
            model_name='dnsinformation',
            name='DnsPremium',
        ),
        migrations.RemoveField(
            model_name='dnsinformation',
            name='DnsPrivacy',
        ),
        migrations.RemoveField(
            model_name='dnsinformation',
            name='DnsSsl',
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='DomainSsl',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnsinformation',
            name='DnsStatus',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnsinformation',
            name='DomainAutoRenew',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnsinformation',
            name='DomainPremium',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnsinformation',
            name='DomainSsl',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
