# Generated by Django 3.2.6 on 2021-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0011_dnsinformation_domainyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='icannmodel',
            name='DomainYear',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
