# Generated by Django 3.2.6 on 2021-09-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0012_icannmodel_domainyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsinformation',
            name='DnsTime',
        ),
        migrations.RemoveField(
            model_name='icannmodel',
            name='DnsTime',
        ),
    ]
