# Generated by Django 3.2.6 on 2021-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0013_auto_20210915_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='icannmodel',
            name='CardToken',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='CardholderAddress',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='CardholderEmail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
