# Generated by Django 3.2.6 on 2021-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0014_auto_20210922_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icannmodel',
            name='CardToken',
        ),
        migrations.RemoveField(
            model_name='icannmodel',
            name='CardholderAddress',
        ),
        migrations.RemoveField(
            model_name='icannmodel',
            name='CardholderEmail',
        ),
    ]
