# Generated by Django 3.2.8 on 2021-10-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0016_auto_20211021_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icannmodel',
            old_name='Address',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='icannmodel',
            old_name='DnsStatus',
            new_name='Address2',
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='ContactId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='DnsSecuritySatus',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='PhoneCode',
            field=models.CharField(default=880, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icannmodel',
            name='ZipCode',
            field=models.CharField(default=3100, max_length=50),
            preserve_default=False,
        ),
    ]
