# Generated by Django 3.2.8 on 2021-10-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0017_auto_20211021_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icannmodel',
            old_name='DnsSecuritySatus',
            new_name='DnsSecurityStatus',
        ),
    ]
