# Generated by Django 3.2.8 on 2021-10-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0019_auto_20211021_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonalinformation',
            old_name='ContactId',
            new_name='AdContactId',
        ),
        migrations.AddField(
            model_name='userpersonalinformation',
            name='CustomerId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonalinformation',
            name='ReContactId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
